<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Time Tracker</title>

    <!-- Required for Bootstrap -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo App::config('url') ?>public/style.css">
</head>
<body>

<header>
    <nav class="navbar navbar-default">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo App::config('url') ?>form/index">Write it down</a></li>
                <li><a href="<?php echo App::config('url') ?>form/listIt">List it</a></li>

            </ul>
        </div>
    </nav>
</header>

    <!-- Main content from view -->
    <main class="container">
        <?php echo $content ?>
    </main>

    <footer class="footer">
        <p class="container">Time Tracker, 2017</p>
    </footer>

    <!-- Bootstrap JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>